import { describe, expect, test } from "bun:test";
import { resolve } from "node:path";

for (const name of [
  "backtest",
  "finance_setup",
  "finance_calendar",
  "finance_charts",
  "finance_data_quality",
  "finance_dataset",
  "finance_sources",
  "finance_track_status",
  "cn_setup",
  "cn_stock_sector_concept",
  "cn_disclosures",
  "cn_market_calendar",
  "cn_market_data",
  "cn_ohlcv",
  "cn_ohlcv_gaps",
  "cn_fundamentals",
  "cn_market_rules",
  "company_profile",
  "day_workbench",
  "hk_setup",
  "hk_disclosures",
  "hk_market_calendar",
  "hk_market_data",
  "hk_ohlcv",
  "hk_ohlcv_gaps",
  "hk_fundamentals",
  "hk_market_rules",
  "order_simulator",
  "portfolio",
  "portfolio_risk",
  "macro_fred",
  "investor_workbench",
  "quant_research",
  "finance_guardrails",
  "finance_news",
  "finance_symbols",
  "sec_edgar",
  "sec_xbrl",
  "stock_fundamentals",
  "stock_corporate_actions",
  "stock_earnings_calendar",
  "stock_research_report",
  "stock_screener",
  "stock_history",
  "stock_market_calendar",
  "stock_order_book",
  "stock_market_snapshot",
  "stock_quote",
  "stock_technicals",
  "swing_workbench",
  "trade_plan",
  "trade_journal",
  "watchlist",
  "us_market_calendar",
  "us_market_rules",
  "us_ohlcv_gaps",
  "us_quote",
  "us_ohlcv",
]) {
  describe(`${name} artifact`, () => {
    test("exports a Pi extension factory", async () => {
      const artifact = resolve(import.meta.dir, `../../dist/${name}/index.js`);
      const module = await import(`${artifact}?test=${Date.now()}`);
      expect(typeof module.default).toBe("function");
    });
  });
}
